# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connection_create <- function(host, user, password, db, port, unix_socket, client_flag, groups, default_file) {
    .Call('RMySQL_connection_create', PACKAGE = 'RMySQL', host, user, password, db, port, unix_socket, client_flag, groups, default_file)
}

connection_release <- function(con) {
    invisible(.Call('RMySQL_connection_release', PACKAGE = 'RMySQL', con))
}

connection_info <- function(con) {
    .Call('RMySQL_connection_info', PACKAGE = 'RMySQL', con)
}

connection_valid <- function(con) {
    .Call('RMySQL_connection_valid', PACKAGE = 'RMySQL', con)
}

connection_quote_string <- function(con, input) {
    .Call('RMySQL_connection_quote_string', PACKAGE = 'RMySQL', con, input)
}

result_create <- function(con, sql) {
    .Call('RMySQL_result_create', PACKAGE = 'RMySQL', con, sql)
}

result_column_info <- function(rs) {
    .Call('RMySQL_result_column_info', PACKAGE = 'RMySQL', rs)
}

