# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connection_create <- function(host, user, password, db, port, unix_socket, client_flag, groups, default_file, ssl_key, ssl_cert, ssl_ca, ssl_capath, ssl_cipher) {
    .Call('RMySQL_connection_create', PACKAGE = 'RMySQL', host, user, password, db, port, unix_socket, client_flag, groups, default_file, ssl_key, ssl_cert, ssl_ca, ssl_capath, ssl_cipher)
}

connection_release <- function(con) {
    invisible(.Call('RMySQL_connection_release', PACKAGE = 'RMySQL', con))
}

connection_info <- function(con) {
    .Call('RMySQL_connection_info', PACKAGE = 'RMySQL', con)
}

connection_valid <- function(con) {
    .Call('RMySQL_connection_valid', PACKAGE = 'RMySQL', con)
}

connection_quote_string <- function(con, input) {
    .Call('RMySQL_connection_quote_string', PACKAGE = 'RMySQL', con, input)
}

connection_exec <- function(con, sql) {
    .Call('RMySQL_connection_exec', PACKAGE = 'RMySQL', con, sql)
}

result_create <- function(con, sql) {
    .Call('RMySQL_result_create', PACKAGE = 'RMySQL', con, sql)
}

result_column_info <- function(rs) {
    .Call('RMySQL_result_column_info', PACKAGE = 'RMySQL', rs)
}

result_fetch <- function(rs, n) {
    .Call('RMySQL_result_fetch', PACKAGE = 'RMySQL', rs, n)
}

result_bind <- function(rs, params) {
    invisible(.Call('RMySQL_result_bind', PACKAGE = 'RMySQL', rs, params))
}

result_bind_rows <- function(rs, params) {
    invisible(.Call('RMySQL_result_bind_rows', PACKAGE = 'RMySQL', rs, params))
}

result_release <- function(rs) {
    invisible(.Call('RMySQL_result_release', PACKAGE = 'RMySQL', rs))
}

result_rows_affected <- function(rs) {
    .Call('RMySQL_result_rows_affected', PACKAGE = 'RMySQL', rs)
}

result_rows_fetched <- function(rs) {
    .Call('RMySQL_result_rows_fetched', PACKAGE = 'RMySQL', rs)
}

result_complete <- function(rs) {
    .Call('RMySQL_result_complete', PACKAGE = 'RMySQL', rs)
}

result_active <- function(rs) {
    .Call('RMySQL_result_active', PACKAGE = 'RMySQL', rs)
}

version <- function() {
    .Call('RMySQL_version', PACKAGE = 'RMySQL')
}

